# Copyright 2025-2026 Sarthak Siddhpura
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.12-alpine

WORKDIR /usr/local/bin
COPY cloudai-benchmark /usr/local/bin/cloudai-benchmark
RUN chmod +x /usr/local/bin/cloudai-benchmark && mkdir -p /output

ENTRYPOINT ["cloudai-benchmark"]
