# Copyright 2025-2026 Sarthak Siddhpura
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.12-slim

WORKDIR /opt/cloudai

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY proto ./proto
COPY agentic_scheduler ./agentic_scheduler

ENV PYTHONPATH=/opt/cloudai
ENV PPO_GRPC_ADDR=0.0.0.0:50061
ENV PPO_MODEL_PATH=/opt/cloudai/models/ppo_latest.pt
ENV PPO_ONLINE_UPDATES_ENABLED=false

EXPOSE 50061

ENTRYPOINT ["python3", "-m", "agentic_scheduler.server"]
