@startuml worker-registration

/'
 Copyright 2025-2026 Sarthak Siddhpura

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
'/

title Worker Registration Flow

participant "Worker" as W
participant "Master" as M
database "Database" as DB

W -> M : RegisterWorker(WorkerInfo)
note right of W
    WorkerInfo:
    - worker_id
    - worker_ip
    - total_cpu
    - total_memory
    - total_storage
    - total_storage
end note

M -> DB : Store worker info
DB --> M : OK

M --> W : RegisterAck(success: true)

M -> W : MasterRegister(master_id, master_address)

@enduml
