# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scheduler_pb2 as scheduler__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlannerStub(object):
    """///////////////////////////////////////////////////////////////
    Planner service
    ///////////////////////////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Plan = channel.unary_unary(
                '/scheduler.Planner/Plan',
                request_serializer=scheduler__pb2.PlanRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PlanResponse.FromString,
                _registered_method=True)
        self.Replan = channel.unary_unary(
                '/scheduler.Planner/Replan',
                request_serializer=scheduler__pb2.ReplanRequest.SerializeToString,
                response_deserializer=scheduler__pb2.PlanResponse.FromString,
                _registered_method=True)


class PlannerServicer(object):
    """///////////////////////////////////////////////////////////////
    Planner service
    ///////////////////////////////////////////////////////////////

    """

    def Plan(self, request, context):
        """Compute a plan for the provided tasks and workers. Planner should
        attempt to respect planning_time_budget_sec and objectives.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replan(self, request, context):
        """Replan based on events and optional previous plan id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Plan': grpc.unary_unary_rpc_method_handler(
                    servicer.Plan,
                    request_deserializer=scheduler__pb2.PlanRequest.FromString,
                    response_serializer=scheduler__pb2.PlanResponse.SerializeToString,
            ),
            'Replan': grpc.unary_unary_rpc_method_handler(
                    servicer.Replan,
                    request_deserializer=scheduler__pb2.ReplanRequest.FromString,
                    response_serializer=scheduler__pb2.PlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.Planner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.Planner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Planner(object):
    """///////////////////////////////////////////////////////////////
    Planner service
    ///////////////////////////////////////////////////////////////

    """

    @staticmethod
    def Plan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Planner/Plan',
            scheduler__pb2.PlanRequest.SerializeToString,
            scheduler__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.Planner/Replan',
            scheduler__pb2.ReplanRequest.SerializeToString,
            scheduler__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
