// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: scheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecPreference int32

const (
	ExecPreference_EXEC_ANY       ExecPreference = 0
	ExecPreference_EXEC_CONTAINER ExecPreference = 1
	ExecPreference_EXEC_VM        ExecPreference = 2
)

// Enum value maps for ExecPreference.
var (
	ExecPreference_name = map[int32]string{
		0: "EXEC_ANY",
		1: "EXEC_CONTAINER",
		2: "EXEC_VM",
	}
	ExecPreference_value = map[string]int32{
		"EXEC_ANY":       0,
		"EXEC_CONTAINER": 1,
		"EXEC_VM":        2,
	}
)

func (x ExecPreference) Enum() *ExecPreference {
	p := new(ExecPreference)
	*p = x
	return p
}

func (x ExecPreference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecPreference) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_proto_enumTypes[0].Descriptor()
}

func (ExecPreference) Type() protoreflect.EnumType {
	return &file_scheduler_proto_enumTypes[0]
}

func (x ExecPreference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecPreference.Descriptor instead.
func (ExecPreference) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

type ExecutionMode int32

const (
	ExecutionMode_MODE_UNKNOWN   ExecutionMode = 0
	ExecutionMode_MODE_CONTAINER ExecutionMode = 1
	ExecutionMode_MODE_VM        ExecutionMode = 2
)

// Enum value maps for ExecutionMode.
var (
	ExecutionMode_name = map[int32]string{
		0: "MODE_UNKNOWN",
		1: "MODE_CONTAINER",
		2: "MODE_VM",
	}
	ExecutionMode_value = map[string]int32{
		"MODE_UNKNOWN":   0,
		"MODE_CONTAINER": 1,
		"MODE_VM":        2,
	}
)

func (x ExecutionMode) Enum() *ExecutionMode {
	p := new(ExecutionMode)
	*p = x
	return p
}

func (x ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_proto_enumTypes[1].Descriptor()
}

func (ExecutionMode) Type() protoreflect.EnumType {
	return &file_scheduler_proto_enumTypes[1]
}

func (x ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMode.Descriptor instead.
func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

type Objective_Type int32

const (
	Objective_MIN_MAKESPAN        Objective_Type = 0
	Objective_MIN_ENERGY          Objective_Type = 1
	Objective_MIN_COST            Objective_Type = 2
	Objective_MIN_LATENCY         Objective_Type = 3
	Objective_MIN_DEADLINE_MISSES Objective_Type = 4
	Objective_MAX_UTILIZATION     Objective_Type = 5
	Objective_CUSTOM              Objective_Type = 6
)

// Enum value maps for Objective_Type.
var (
	Objective_Type_name = map[int32]string{
		0: "MIN_MAKESPAN",
		1: "MIN_ENERGY",
		2: "MIN_COST",
		3: "MIN_LATENCY",
		4: "MIN_DEADLINE_MISSES",
		5: "MAX_UTILIZATION",
		6: "CUSTOM",
	}
	Objective_Type_value = map[string]int32{
		"MIN_MAKESPAN":        0,
		"MIN_ENERGY":          1,
		"MIN_COST":            2,
		"MIN_LATENCY":         3,
		"MIN_DEADLINE_MISSES": 4,
		"MAX_UTILIZATION":     5,
		"CUSTOM":              6,
	}
)

func (x Objective_Type) Enum() *Objective_Type {
	p := new(Objective_Type)
	*p = x
	return p
}

func (x Objective_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Objective_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_proto_enumTypes[2].Descriptor()
}

func (Objective_Type) Type() protoreflect.EnumType {
	return &file_scheduler_proto_enumTypes[2]
}

func (x Objective_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Objective_Type.Descriptor instead.
func (Objective_Type) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{6, 0}
}

type PlannerEvent_Type int32

const (
	PlannerEvent_WORKER_DOWN       PlannerEvent_Type = 0
	PlannerEvent_ASSIGNMENT_FAILED PlannerEvent_Type = 1
	PlannerEvent_TASK_CANCELLED    PlannerEvent_Type = 2
	PlannerEvent_WORKER_ADDED      PlannerEvent_Type = 3
	PlannerEvent_WORKER_UPDATED    PlannerEvent_Type = 4
	PlannerEvent_CUSTOM            PlannerEvent_Type = 5
)

// Enum value maps for PlannerEvent_Type.
var (
	PlannerEvent_Type_name = map[int32]string{
		0: "WORKER_DOWN",
		1: "ASSIGNMENT_FAILED",
		2: "TASK_CANCELLED",
		3: "WORKER_ADDED",
		4: "WORKER_UPDATED",
		5: "CUSTOM",
	}
	PlannerEvent_Type_value = map[string]int32{
		"WORKER_DOWN":       0,
		"ASSIGNMENT_FAILED": 1,
		"TASK_CANCELLED":    2,
		"WORKER_ADDED":      3,
		"WORKER_UPDATED":    4,
		"CUSTOM":            5,
	}
)

func (x PlannerEvent_Type) Enum() *PlannerEvent_Type {
	p := new(PlannerEvent_Type)
	*p = x
	return p
}

func (x PlannerEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlannerEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_proto_enumTypes[3].Descriptor()
}

func (PlannerEvent_Type) Type() protoreflect.EnumType {
	return &file_scheduler_proto_enumTypes[3]
}

func (x PlannerEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlannerEvent_Type.Descriptor instead.
func (PlannerEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{12, 0}
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CpuReq         float64                `protobuf:"fixed64,2,opt,name=cpu_req,json=cpuReq,proto3" json:"cpu_req,omitempty"`                                                       // number of cores (can be fractional)
	MemMb          int32                  `protobuf:"varint,3,opt,name=mem_mb,json=memMb,proto3" json:"mem_mb,omitempty"`                                                           // memory requirement in MB
	GpuReq         int32                  `protobuf:"varint,4,opt,name=gpu_req,json=gpuReq,proto3" json:"gpu_req,omitempty"`                                                        // number of GPUs required
	DiskMb         int32                  `protobuf:"varint,20,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`                                                       // optional disk requirement in MB
	NetworkMbps    int32                  `protobuf:"varint,21,opt,name=network_mbps,json=networkMbps,proto3" json:"network_mbps,omitempty"`                                        // optional network bandwidth requirement
	TaskType       string                 `protobuf:"bytes,5,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`                                                   // semantic type (for predictor / grouping)
	EstimatedSec   int64                  `protobuf:"varint,6,opt,name=estimated_sec,json=estimatedSec,proto3" json:"estimated_sec,omitempty"`                                      // estimated runtime in seconds (optional)
	Priority       int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`                                                                  // higher = more urgent
	DeadlineUnix   int64                  `protobuf:"varint,8,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`                                      // unix seconds; 0 = no deadline
	Meta           map[string]string      `protobuf:"bytes,9,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // free-form metadata
	ContainerImage string                 `protobuf:"bytes,10,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`                                // image for container execution
	Command        []string               `protobuf:"bytes,11,rep,name=command,proto3" json:"command,omitempty"`                                                                    // command and args
	ExecPref       ExecPreference         `protobuf:"varint,12,opt,name=exec_pref,json=execPref,proto3,enum=scheduler.ExecPreference" json:"exec_pref,omitempty"`                   // prefer CONTAINER, VM, or ANY
	Checkpointable bool                   `protobuf:"varint,13,opt,name=checkpointable,proto3" json:"checkpointable,omitempty"`                                                     // whether the task supports checkpoint/resume
	Tenant         string                 `protobuf:"bytes,14,opt,name=tenant,proto3" json:"tenant,omitempty"`                                                                      // multi-tenant identifier
	Labels         []string               `protobuf:"bytes,15,rep,name=labels,proto3" json:"labels,omitempty"`                                                                      // free-form labels used for affinity
	Extra          *structpb.Struct       `protobuf:"bytes,16,opt,name=extra,proto3" json:"extra,omitempty"`                                                                        // extensible structured metadata (JSON-like)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetCpuReq() float64 {
	if x != nil {
		return x.CpuReq
	}
	return 0
}

func (x *Task) GetMemMb() int32 {
	if x != nil {
		return x.MemMb
	}
	return 0
}

func (x *Task) GetGpuReq() int32 {
	if x != nil {
		return x.GpuReq
	}
	return 0
}

func (x *Task) GetDiskMb() int32 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

func (x *Task) GetNetworkMbps() int32 {
	if x != nil {
		return x.NetworkMbps
	}
	return 0
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetEstimatedSec() int64 {
	if x != nil {
		return x.EstimatedSec
	}
	return 0
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *Task) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Task) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *Task) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Task) GetExecPref() ExecPreference {
	if x != nil {
		return x.ExecPref
	}
	return ExecPreference_EXEC_ANY
}

func (x *Task) GetCheckpointable() bool {
	if x != nil {
		return x.Checkpointable
	}
	return false
}

func (x *Task) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Task) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Task) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TotalCpu      float64                `protobuf:"fixed64,2,opt,name=total_cpu,json=totalCpu,proto3" json:"total_cpu,omitempty"` // total cores
	TotalMem      int32                  `protobuf:"varint,3,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"`  // MB
	Gpus          int32                  `protobuf:"varint,4,opt,name=gpus,proto3" json:"gpus,omitempty"`
	TotalDiskMb   int32                  `protobuf:"varint,22,opt,name=total_disk_mb,json=totalDiskMb,proto3" json:"total_disk_mb,omitempty"`
	Labels        []string               `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`                                                                        // e.g. ["gpu","arm","zone-a"]
	FreeCpu       float64                `protobuf:"fixed64,6,opt,name=free_cpu,json=freeCpu,proto3" json:"free_cpu,omitempty"`                                                     // snapshot free
	FreeMem       int32                  `protobuf:"varint,7,opt,name=free_mem,json=freeMem,proto3" json:"free_mem,omitempty"`                                                      // snapshot free
	FreeGpus      int32                  `protobuf:"varint,8,opt,name=free_gpus,json=freeGpus,proto3" json:"free_gpus,omitempty"`                                                   // snapshot free
	LastSeenUnix  int64                  `protobuf:"varint,9,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`                                     // timestamp of last heartbeat
	ExecModes     []ExecutionMode        `protobuf:"varint,10,rep,packed,name=exec_modes,json=execModes,proto3,enum=scheduler.ExecutionMode" json:"exec_modes,omitempty"`           // supported execution types (VM/CONTAINER)
	Architecture  string                 `protobuf:"bytes,11,opt,name=architecture,proto3" json:"architecture,omitempty"`                                                           // e.g. "x86_64", "aarch64"
	Accelerators  []string               `protobuf:"bytes,12,rep,name=accelerators,proto3" json:"accelerators,omitempty"`                                                           // e.g., ["nvidia-tesla-v100"]
	Zone          string                 `protobuf:"bytes,13,opt,name=zone,proto3" json:"zone,omitempty"`                                                                           // availability zone or rack id
	Meta          map[string]string      `protobuf:"bytes,14,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // extra data (capacity classes etc.)
	Extra         *structpb.Struct       `protobuf:"bytes,15,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *Worker) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Worker) GetTotalCpu() float64 {
	if x != nil {
		return x.TotalCpu
	}
	return 0
}

func (x *Worker) GetTotalMem() int32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *Worker) GetGpus() int32 {
	if x != nil {
		return x.Gpus
	}
	return 0
}

func (x *Worker) GetTotalDiskMb() int32 {
	if x != nil {
		return x.TotalDiskMb
	}
	return 0
}

func (x *Worker) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Worker) GetFreeCpu() float64 {
	if x != nil {
		return x.FreeCpu
	}
	return 0
}

func (x *Worker) GetFreeMem() int32 {
	if x != nil {
		return x.FreeMem
	}
	return 0
}

func (x *Worker) GetFreeGpus() int32 {
	if x != nil {
		return x.FreeGpus
	}
	return 0
}

func (x *Worker) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

func (x *Worker) GetExecModes() []ExecutionMode {
	if x != nil {
		return x.ExecModes
	}
	return nil
}

func (x *Worker) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Worker) GetAccelerators() []string {
	if x != nil {
		return x.Accelerators
	}
	return nil
}

func (x *Worker) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Worker) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Worker) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	FreeCpu       float64                `protobuf:"fixed64,2,opt,name=free_cpu,json=freeCpu,proto3" json:"free_cpu,omitempty"`
	FreeMem       int32                  `protobuf:"varint,3,opt,name=free_mem,json=freeMem,proto3" json:"free_mem,omitempty"`
	FreeGpus      int32                  `protobuf:"varint,4,opt,name=free_gpus,json=freeGpus,proto3" json:"free_gpus,omitempty"`
	RunningTasks  int32                  `protobuf:"varint,5,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	Labels        []string               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Extra         *structpb.Struct       `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Heartbeat) GetFreeCpu() float64 {
	if x != nil {
		return x.FreeCpu
	}
	return 0
}

func (x *Heartbeat) GetFreeMem() int32 {
	if x != nil {
		return x.FreeMem
	}
	return 0
}

func (x *Heartbeat) GetFreeGpus() int32 {
	if x != nil {
		return x.FreeGpus
	}
	return 0
}

func (x *Heartbeat) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *Heartbeat) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Heartbeat) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *Heartbeat) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type AssignRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId       string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	StartUnix      int64                  `protobuf:"varint,3,opt,name=start_unix,json=startUnix,proto3" json:"start_unix,omitempty"` // start time in unix seconds (0 => ASAP)
	EstDurationSec int64                  `protobuf:"varint,4,opt,name=est_duration_sec,json=estDurationSec,proto3" json:"est_duration_sec,omitempty"`
	ExecMode       ExecutionMode          `protobuf:"varint,5,opt,name=exec_mode,json=execMode,proto3,enum=scheduler.ExecutionMode" json:"exec_mode,omitempty"`
	ContainerImage string                 `protobuf:"bytes,6,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	Meta           map[string]string      `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignRequest) Reset() {
	*x = AssignRequest{}
	mi := &file_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRequest) ProtoMessage() {}

func (x *AssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRequest.ProtoReflect.Descriptor instead.
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *AssignRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AssignRequest) GetStartUnix() int64 {
	if x != nil {
		return x.StartUnix
	}
	return 0
}

func (x *AssignRequest) GetEstDurationSec() int64 {
	if x != nil {
		return x.EstDurationSec
	}
	return 0
}

func (x *AssignRequest) GetExecMode() ExecutionMode {
	if x != nil {
		return x.ExecMode
	}
	return ExecutionMode_MODE_UNKNOWN
}

func (x *AssignRequest) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *AssignRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type AssignAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                              // if not accepted
	ContainerId   string                 `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // optional
	VmId          string                 `protobuf:"bytes,6,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                      // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignAck) Reset() {
	*x = AssignAck{}
	mi := &file_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAck) ProtoMessage() {}

func (x *AssignAck) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAck.ProtoReflect.Descriptor instead.
func (*AssignAck) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *AssignAck) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssignAck) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AssignAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AssignAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AssignAck) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *AssignAck) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type PlanRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Tasks   []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`     // pending tasks to schedule (batch)
	Workers []*Worker              `protobuf:"bytes,2,rep,name=workers,proto3" json:"workers,omitempty"` // current worker snapshots (capacity)
	// objectives & constraints
	Objectives  []*Objective  `protobuf:"bytes,3,rep,name=objectives,proto3" json:"objectives,omitempty"`
	Constraints []*Constraint `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty"`
	// planning options / knobs
	PlanningTimeBudgetSec float64      `protobuf:"fixed64,10,opt,name=planning_time_budget_sec,json=planningTimeBudgetSec,proto3" json:"planning_time_budget_sec,omitempty"` // planner should attempt to respect this
	PreviousPlanId        string       `protobuf:"bytes,11,opt,name=previous_plan_id,json=previousPlanId,proto3" json:"previous_plan_id,omitempty"`                          // optional: planner can reuse previous plan
	Options               *PlanOptions `protobuf:"bytes,12,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlanRequest) Reset() {
	*x = PlanRequest{}
	mi := &file_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRequest) ProtoMessage() {}

func (x *PlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRequest.ProtoReflect.Descriptor instead.
func (*PlanRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *PlanRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *PlanRequest) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *PlanRequest) GetObjectives() []*Objective {
	if x != nil {
		return x.Objectives
	}
	return nil
}

func (x *PlanRequest) GetConstraints() []*Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *PlanRequest) GetPlanningTimeBudgetSec() float64 {
	if x != nil {
		return x.PlanningTimeBudgetSec
	}
	return 0
}

func (x *PlanRequest) GetPreviousPlanId() string {
	if x != nil {
		return x.PreviousPlanId
	}
	return ""
}

func (x *PlanRequest) GetOptions() *PlanOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type Objective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Objective_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=scheduler.Objective_Type" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`         // relative importance among objectives
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // optional human-readable description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Objective) Reset() {
	*x = Objective{}
	mi := &file_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Objective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objective) ProtoMessage() {}

func (x *Objective) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objective.ProtoReflect.Descriptor instead.
func (*Objective) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *Objective) GetType() Objective_Type {
	if x != nil {
		return x.Type
	}
	return Objective_MIN_MAKESPAN
}

func (x *Objective) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Objective) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Constraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// generic key/value for extensibility; planner interprets specific keys.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // e.g. "max_tasks_per_worker", "require_gpu"
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // e.g. "4", "true"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *Constraint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Constraint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PlanOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllowPreemption bool                   `protobuf:"varint,1,opt,name=allow_preemption,json=allowPreemption,proto3" json:"allow_preemption,omitempty"`
	PreferLocality  bool                   `protobuf:"varint,2,opt,name=prefer_locality,json=preferLocality,proto3" json:"prefer_locality,omitempty"`
	MaxAssignments  int32                  `protobuf:"varint,3,opt,name=max_assignments,json=maxAssignments,proto3" json:"max_assignments,omitempty"` // limit number of assignments returned
	// other knobs can be passed in 'extra'
	Extra         *structpb.Struct `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanOptions) Reset() {
	*x = PlanOptions{}
	mi := &file_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanOptions) ProtoMessage() {}

func (x *PlanOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanOptions.ProtoReflect.Descriptor instead.
func (*PlanOptions) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *PlanOptions) GetAllowPreemption() bool {
	if x != nil {
		return x.AllowPreemption
	}
	return false
}

func (x *PlanOptions) GetPreferLocality() bool {
	if x != nil {
		return x.PreferLocality
	}
	return false
}

func (x *PlanOptions) GetMaxAssignments() int32 {
	if x != nil {
		return x.MaxAssignments
	}
	return 0
}

func (x *PlanOptions) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Assignment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId       string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	StartUnix      int64                  `protobuf:"varint,3,opt,name=start_unix,json=startUnix,proto3" json:"start_unix,omitempty"`
	EstDurationSec int64                  `protobuf:"varint,4,opt,name=est_duration_sec,json=estDurationSec,proto3" json:"est_duration_sec,omitempty"`
	ExecMode       ExecutionMode          `protobuf:"varint,5,opt,name=exec_mode,json=execMode,proto3,enum=scheduler.ExecutionMode" json:"exec_mode,omitempty"`
	ContainerImage string                 `protobuf:"bytes,6,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	VmSpec         string                 `protobuf:"bytes,7,opt,name=vm_spec,json=vmSpec,proto3" json:"vm_spec,omitempty"`
	Meta           map[string]string      `protobuf:"bytes,8,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Score          float64                `protobuf:"fixed64,9,opt,name=score,proto3" json:"score,omitempty"` // planner's score contribution for the assignment
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *Assignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Assignment) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Assignment) GetStartUnix() int64 {
	if x != nil {
		return x.StartUnix
	}
	return 0
}

func (x *Assignment) GetEstDurationSec() int64 {
	if x != nil {
		return x.EstDurationSec
	}
	return 0
}

func (x *Assignment) GetExecMode() ExecutionMode {
	if x != nil {
		return x.ExecMode
	}
	return ExecutionMode_MODE_UNKNOWN
}

func (x *Assignment) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *Assignment) GetVmSpec() string {
	if x != nil {
		return x.VmSpec
	}
	return ""
}

func (x *Assignment) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Assignment) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type PlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Assignments   []*Assignment          `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	StatusMessage string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	GeneratedTs   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=generated_ts,json=generatedTs,proto3" json:"generated_ts,omitempty"`
	Warnings      []string               `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Extra         *structpb.Struct       `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"` // planner-specific metadata (like stats)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponse) Reset() {
	*x = PlanResponse{}
	mi := &file_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponse) ProtoMessage() {}

func (x *PlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponse.ProtoReflect.Descriptor instead.
func (*PlanResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *PlanResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanResponse) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *PlanResponse) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *PlanResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *PlanResponse) GetGeneratedTs() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedTs
	}
	return nil
}

func (x *PlanResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *PlanResponse) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type ReplanRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PreviousPlanId        string                 `protobuf:"bytes,1,opt,name=previous_plan_id,json=previousPlanId,proto3" json:"previous_plan_id,omitempty"`
	Tasks                 []*Task                `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Workers               []*Worker              `protobuf:"bytes,3,rep,name=workers,proto3" json:"workers,omitempty"`
	Events                []*PlannerEvent        `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"` // e.g. worker down, assignment failed
	PlanningTimeBudgetSec float64                `protobuf:"fixed64,5,opt,name=planning_time_budget_sec,json=planningTimeBudgetSec,proto3" json:"planning_time_budget_sec,omitempty"`
	Options               *PlanOptions           `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReplanRequest) Reset() {
	*x = ReplanRequest{}
	mi := &file_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplanRequest) ProtoMessage() {}

func (x *ReplanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplanRequest.ProtoReflect.Descriptor instead.
func (*ReplanRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *ReplanRequest) GetPreviousPlanId() string {
	if x != nil {
		return x.PreviousPlanId
	}
	return ""
}

func (x *ReplanRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ReplanRequest) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *ReplanRequest) GetEvents() []*PlannerEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ReplanRequest) GetPlanningTimeBudgetSec() float64 {
	if x != nil {
		return x.PlanningTimeBudgetSec
	}
	return 0
}

func (x *ReplanRequest) GetOptions() *PlanOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type PlannerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PlannerEvent_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=scheduler.PlannerEvent_Type" json:"type,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"` // worker id or task id
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Extra         *structpb.Struct       `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlannerEvent) Reset() {
	*x = PlannerEvent{}
	mi := &file_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlannerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlannerEvent) ProtoMessage() {}

func (x *PlannerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlannerEvent.ProtoReflect.Descriptor instead.
func (*PlannerEvent) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *PlannerEvent) GetType() PlannerEvent_Type {
	if x != nil {
		return x.Type
	}
	return PlannerEvent_WORKER_DOWN
}

func (x *PlannerEvent) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *PlannerEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlannerEvent) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *PlannerEvent) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRequest) Reset() {
	*x = GetTaskStatusRequest{}
	mi := &file_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRequest) ProtoMessage() {}

func (x *GetTaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *GetTaskStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusResponse) Reset() {
	*x = GetTaskStatusResponse{}
	mi := &file_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusResponse) ProtoMessage() {}

func (x *GetTaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *GetTaskStatusResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskStatusResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GetTaskStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{18}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worker        *Worker                `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterWorkerRequest) GetWorker() *Worker {
	if x != nil {
		return x.Worker
	}
	return nil
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Worker         *Worker                `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
	RunningTaskIds []string               `protobuf:"bytes,2,rep,name=running_task_ids,json=runningTaskIds,proto3" json:"running_task_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_scheduler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetWorker() *Worker {
	if x != nil {
		return x.Worker
	}
	return nil
}

func (x *HeartbeatRequest) GetRunningTaskIds() []string {
	if x != nil {
		return x.RunningTaskIds
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TasksToCancel []string               `protobuf:"bytes,2,rep,name=tasks_to_cancel,json=tasksToCancel,proto3" json:"tasks_to_cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_scheduler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetTasksToCancel() []string {
	if x != nil {
		return x.TasksToCancel
	}
	return nil
}

type ListWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersRequest) Reset() {
	*x = ListWorkersRequest{}
	mi := &file_scheduler_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersRequest) ProtoMessage() {}

func (x *ListWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersRequest.ProtoReflect.Descriptor instead.
func (*ListWorkersRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{23}
}

type ListWorkersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*Worker              `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkersResponse) Reset() {
	*x = ListWorkersResponse{}
	mi := &file_scheduler_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkersResponse) ProtoMessage() {}

func (x *ListWorkersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkersResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{24}
}

func (x *ListWorkersResponse) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

type TaskCompletionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId          string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Success           bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ActualDurationSec int64                  `protobuf:"varint,5,opt,name=actual_duration_sec,json=actualDurationSec,proto3" json:"actual_duration_sec,omitempty"`
	ResourceUsage     map[string]float64     `protobuf:"bytes,6,rep,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskCompletionRequest) Reset() {
	*x = TaskCompletionRequest{}
	mi := &file_scheduler_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionRequest) ProtoMessage() {}

func (x *TaskCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionRequest.ProtoReflect.Descriptor instead.
func (*TaskCompletionRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{25}
}

func (x *TaskCompletionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompletionRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TaskCompletionRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskCompletionRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskCompletionRequest) GetActualDurationSec() int64 {
	if x != nil {
		return x.ActualDurationSec
	}
	return 0
}

func (x *TaskCompletionRequest) GetResourceUsage() map[string]float64 {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

type TaskCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionResponse) Reset() {
	*x = TaskCompletionResponse{}
	mi := &file_scheduler_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionResponse) ProtoMessage() {}

func (x *TaskCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionResponse.ProtoReflect.Descriptor instead.
func (*TaskCompletionResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{26}
}

func (x *TaskCompletionResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\tscheduler\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x88\x05\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acpu_req\x18\x02 \x01(\x01R\x06cpuReq\x12\x15\n" +
	"\x06mem_mb\x18\x03 \x01(\x05R\x05memMb\x12\x17\n" +
	"\agpu_req\x18\x04 \x01(\x05R\x06gpuReq\x12\x17\n" +
	"\adisk_mb\x18\x14 \x01(\x05R\x06diskMb\x12!\n" +
	"\fnetwork_mbps\x18\x15 \x01(\x05R\vnetworkMbps\x12\x1b\n" +
	"\ttask_type\x18\x05 \x01(\tR\btaskType\x12#\n" +
	"\restimated_sec\x18\x06 \x01(\x03R\festimatedSec\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12#\n" +
	"\rdeadline_unix\x18\b \x01(\x03R\fdeadlineUnix\x12-\n" +
	"\x04meta\x18\t \x03(\v2\x19.scheduler.Task.MetaEntryR\x04meta\x12'\n" +
	"\x0fcontainer_image\x18\n" +
	" \x01(\tR\x0econtainerImage\x12\x18\n" +
	"\acommand\x18\v \x03(\tR\acommand\x126\n" +
	"\texec_pref\x18\f \x01(\x0e2\x19.scheduler.ExecPreferenceR\bexecPref\x12&\n" +
	"\x0echeckpointable\x18\r \x01(\bR\x0echeckpointable\x12\x16\n" +
	"\x06tenant\x18\x0e \x01(\tR\x06tenant\x12\x16\n" +
	"\x06labels\x18\x0f \x03(\tR\x06labels\x12-\n" +
	"\x05extra\x18\x10 \x01(\v2\x17.google.protobuf.StructR\x05extra\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x04\n" +
	"\x06Worker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttotal_cpu\x18\x02 \x01(\x01R\btotalCpu\x12\x1b\n" +
	"\ttotal_mem\x18\x03 \x01(\x05R\btotalMem\x12\x12\n" +
	"\x04gpus\x18\x04 \x01(\x05R\x04gpus\x12\"\n" +
	"\rtotal_disk_mb\x18\x16 \x01(\x05R\vtotalDiskMb\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labels\x12\x19\n" +
	"\bfree_cpu\x18\x06 \x01(\x01R\afreeCpu\x12\x19\n" +
	"\bfree_mem\x18\a \x01(\x05R\afreeMem\x12\x1b\n" +
	"\tfree_gpus\x18\b \x01(\x05R\bfreeGpus\x12$\n" +
	"\x0elast_seen_unix\x18\t \x01(\x03R\flastSeenUnix\x127\n" +
	"\n" +
	"exec_modes\x18\n" +
	" \x03(\x0e2\x18.scheduler.ExecutionModeR\texecModes\x12\"\n" +
	"\farchitecture\x18\v \x01(\tR\farchitecture\x12\"\n" +
	"\faccelerators\x18\f \x03(\tR\faccelerators\x12\x12\n" +
	"\x04zone\x18\r \x01(\tR\x04zone\x12/\n" +
	"\x04meta\x18\x0e \x03(\v2\x1b.scheduler.Worker.MetaEntryR\x04meta\x12-\n" +
	"\x05extra\x18\x0f \x01(\v2\x17.google.protobuf.StructR\x05extra\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\tHeartbeat\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x19\n" +
	"\bfree_cpu\x18\x02 \x01(\x01R\afreeCpu\x12\x19\n" +
	"\bfree_mem\x18\x03 \x01(\x05R\afreeMem\x12\x1b\n" +
	"\tfree_gpus\x18\x04 \x01(\x05R\bfreeGpus\x12#\n" +
	"\rrunning_tasks\x18\x05 \x01(\x05R\frunningTasks\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x12-\n" +
	"\x05extra\x18\a \x01(\v2\x17.google.protobuf.StructR\x05extra\x12*\n" +
	"\x02ts\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"\xdf\x02\n" +
	"\rAssignRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"start_unix\x18\x03 \x01(\x03R\tstartUnix\x12(\n" +
	"\x10est_duration_sec\x18\x04 \x01(\x03R\x0eestDurationSec\x125\n" +
	"\texec_mode\x18\x05 \x01(\x0e2\x18.scheduler.ExecutionModeR\bexecMode\x12'\n" +
	"\x0fcontainer_image\x18\x06 \x01(\tR\x0econtainerImage\x126\n" +
	"\x04meta\x18\a \x03(\v2\".scheduler.AssignRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\tAssignAck\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12!\n" +
	"\fcontainer_id\x18\x05 \x01(\tR\vcontainerId\x12\x13\n" +
	"\x05vm_id\x18\x06 \x01(\tR\x04vmId\"\xe5\x02\n" +
	"\vPlanRequest\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.scheduler.TaskR\x05tasks\x12+\n" +
	"\aworkers\x18\x02 \x03(\v2\x11.scheduler.WorkerR\aworkers\x124\n" +
	"\n" +
	"objectives\x18\x03 \x03(\v2\x14.scheduler.ObjectiveR\n" +
	"objectives\x127\n" +
	"\vconstraints\x18\x04 \x03(\v2\x15.scheduler.ConstraintR\vconstraints\x127\n" +
	"\x18planning_time_budget_sec\x18\n" +
	" \x01(\x01R\x15planningTimeBudgetSec\x12(\n" +
	"\x10previous_plan_id\x18\v \x01(\tR\x0epreviousPlanId\x120\n" +
	"\aoptions\x18\f \x01(\v2\x16.scheduler.PlanOptionsR\aoptions\"\xf8\x01\n" +
	"\tObjective\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.scheduler.Objective.TypeR\x04type\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x81\x01\n" +
	"\x04Type\x12\x10\n" +
	"\fMIN_MAKESPAN\x10\x00\x12\x0e\n" +
	"\n" +
	"MIN_ENERGY\x10\x01\x12\f\n" +
	"\bMIN_COST\x10\x02\x12\x0f\n" +
	"\vMIN_LATENCY\x10\x03\x12\x17\n" +
	"\x13MIN_DEADLINE_MISSES\x10\x04\x12\x13\n" +
	"\x0fMAX_UTILIZATION\x10\x05\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x06\"4\n" +
	"\n" +
	"Constraint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb9\x01\n" +
	"\vPlanOptions\x12)\n" +
	"\x10allow_preemption\x18\x01 \x01(\bR\x0fallowPreemption\x12'\n" +
	"\x0fprefer_locality\x18\x02 \x01(\bR\x0epreferLocality\x12'\n" +
	"\x0fmax_assignments\x18\x03 \x01(\x05R\x0emaxAssignments\x12-\n" +
	"\x05extra\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x05extra\"\x88\x03\n" +
	"\n" +
	"Assignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"start_unix\x18\x03 \x01(\x03R\tstartUnix\x12(\n" +
	"\x10est_duration_sec\x18\x04 \x01(\x03R\x0eestDurationSec\x125\n" +
	"\texec_mode\x18\x05 \x01(\x0e2\x18.scheduler.ExecutionModeR\bexecMode\x12'\n" +
	"\x0fcontainer_image\x18\x06 \x01(\tR\x0econtainerImage\x12\x17\n" +
	"\avm_spec\x18\a \x01(\tR\x06vmSpec\x123\n" +
	"\x04meta\x18\b \x03(\v2\x1f.scheduler.Assignment.MetaEntryR\x04meta\x12\x14\n" +
	"\x05score\x18\t \x01(\x01R\x05score\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x02\n" +
	"\fPlanResponse\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x127\n" +
	"\vassignments\x18\x02 \x03(\v2\x15.scheduler.AssignmentR\vassignments\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\x12=\n" +
	"\fgenerated_ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedTs\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings\x12-\n" +
	"\x05extra\x18\a \x01(\v2\x17.google.protobuf.StructR\x05extra\"\xa9\x02\n" +
	"\rReplanRequest\x12(\n" +
	"\x10previous_plan_id\x18\x01 \x01(\tR\x0epreviousPlanId\x12%\n" +
	"\x05tasks\x18\x02 \x03(\v2\x0f.scheduler.TaskR\x05tasks\x12+\n" +
	"\aworkers\x18\x03 \x03(\v2\x11.scheduler.WorkerR\aworkers\x12/\n" +
	"\x06events\x18\x04 \x03(\v2\x17.scheduler.PlannerEventR\x06events\x127\n" +
	"\x18planning_time_budget_sec\x18\x05 \x01(\x01R\x15planningTimeBudgetSec\x120\n" +
	"\aoptions\x18\x06 \x01(\v2\x16.scheduler.PlanOptionsR\aoptions\"\xd2\x02\n" +
	"\fPlannerEvent\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.scheduler.PlannerEvent.TypeR\x04type\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x02ts\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12-\n" +
	"\x05extra\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05extra\"t\n" +
	"\x04Type\x12\x0f\n" +
	"\vWORKER_DOWN\x10\x00\x12\x15\n" +
	"\x11ASSIGNMENT_FAILED\x10\x01\x12\x12\n" +
	"\x0eTASK_CANCELLED\x10\x02\x12\x10\n" +
	"\fWORKER_ADDED\x10\x03\x12\x12\n" +
	"\x0eWORKER_UPDATED\x10\x04\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x05\"8\n" +
	"\x11SubmitTaskRequest\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.scheduler.TaskR\x04task\"G\n" +
	"\x12SubmitTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x14GetTaskStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x7f\n" +
	"\x15GetTaskStatusResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"H\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x15RegisterWorkerRequest\x12)\n" +
	"\x06worker\x18\x01 \x01(\v2\x11.scheduler.WorkerR\x06worker\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x10HeartbeatRequest\x12)\n" +
	"\x06worker\x18\x01 \x01(\v2\x11.scheduler.WorkerR\x06worker\x12(\n" +
	"\x10running_task_ids\x18\x02 \x03(\tR\x0erunningTaskIds\"U\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0ftasks_to_cancel\x18\x02 \x03(\tR\rtasksToCancel\"\x14\n" +
	"\x12ListWorkersRequest\"B\n" +
	"\x13ListWorkersResponse\x12+\n" +
	"\aworkers\x18\x01 \x03(\v2\x11.scheduler.WorkerR\aworkers\"\xda\x02\n" +
	"\x15TaskCompletionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12.\n" +
	"\x13actual_duration_sec\x18\x05 \x01(\x03R\x11actualDurationSec\x12Z\n" +
	"\x0eresource_usage\x18\x06 \x03(\v23.scheduler.TaskCompletionRequest.ResourceUsageEntryR\rresourceUsage\x1a@\n" +
	"\x12ResourceUsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"<\n" +
	"\x16TaskCompletionResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged*?\n" +
	"\x0eExecPreference\x12\f\n" +
	"\bEXEC_ANY\x10\x00\x12\x12\n" +
	"\x0eEXEC_CONTAINER\x10\x01\x12\v\n" +
	"\aEXEC_VM\x10\x02*B\n" +
	"\rExecutionMode\x12\x10\n" +
	"\fMODE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eMODE_CONTAINER\x10\x01\x12\v\n" +
	"\aMODE_VM\x10\x022\xc6\x04\n" +
	"\x10SchedulerService\x12I\n" +
	"\n" +
	"SubmitTask\x12\x1c.scheduler.SubmitTaskRequest\x1a\x1d.scheduler.SubmitTaskResponse\x12R\n" +
	"\rGetTaskStatus\x12\x1f.scheduler.GetTaskStatusRequest\x1a .scheduler.GetTaskStatusResponse\x12I\n" +
	"\n" +
	"CancelTask\x12\x1c.scheduler.CancelTaskRequest\x1a\x1d.scheduler.CancelTaskResponse\x12U\n" +
	"\x0eRegisterWorker\x12 .scheduler.RegisterWorkerRequest\x1a!.scheduler.RegisterWorkerResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.scheduler.HeartbeatRequest\x1a\x1c.scheduler.HeartbeatResponse\x12L\n" +
	"\vListWorkers\x12\x1d.scheduler.ListWorkersRequest\x1a\x1e.scheduler.ListWorkersResponse\x12[\n" +
	"\x14ReportTaskCompletion\x12 .scheduler.TaskCompletionRequest\x1a!.scheduler.TaskCompletionResponse2\x7f\n" +
	"\aPlanner\x127\n" +
	"\x04Plan\x12\x16.scheduler.PlanRequest\x1a\x17.scheduler.PlanResponse\x12;\n" +
	"\x06Replan\x12\x18.scheduler.ReplanRequest\x1a\x17.scheduler.PlanResponseBM\n" +
	"\x1dcom.yourorg.aischeduler.protoP\x01Z*github.com/Codesmith28/CloudAI/proto;protob\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_scheduler_proto_goTypes = []any{
	(ExecPreference)(0),            // 0: scheduler.ExecPreference
	(ExecutionMode)(0),             // 1: scheduler.ExecutionMode
	(Objective_Type)(0),            // 2: scheduler.Objective.Type
	(PlannerEvent_Type)(0),         // 3: scheduler.PlannerEvent.Type
	(*Task)(nil),                   // 4: scheduler.Task
	(*Worker)(nil),                 // 5: scheduler.Worker
	(*Heartbeat)(nil),              // 6: scheduler.Heartbeat
	(*AssignRequest)(nil),          // 7: scheduler.AssignRequest
	(*AssignAck)(nil),              // 8: scheduler.AssignAck
	(*PlanRequest)(nil),            // 9: scheduler.PlanRequest
	(*Objective)(nil),              // 10: scheduler.Objective
	(*Constraint)(nil),             // 11: scheduler.Constraint
	(*PlanOptions)(nil),            // 12: scheduler.PlanOptions
	(*Assignment)(nil),             // 13: scheduler.Assignment
	(*PlanResponse)(nil),           // 14: scheduler.PlanResponse
	(*ReplanRequest)(nil),          // 15: scheduler.ReplanRequest
	(*PlannerEvent)(nil),           // 16: scheduler.PlannerEvent
	(*SubmitTaskRequest)(nil),      // 17: scheduler.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),     // 18: scheduler.SubmitTaskResponse
	(*GetTaskStatusRequest)(nil),   // 19: scheduler.GetTaskStatusRequest
	(*GetTaskStatusResponse)(nil),  // 20: scheduler.GetTaskStatusResponse
	(*CancelTaskRequest)(nil),      // 21: scheduler.CancelTaskRequest
	(*CancelTaskResponse)(nil),     // 22: scheduler.CancelTaskResponse
	(*RegisterWorkerRequest)(nil),  // 23: scheduler.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 24: scheduler.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),       // 25: scheduler.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 26: scheduler.HeartbeatResponse
	(*ListWorkersRequest)(nil),     // 27: scheduler.ListWorkersRequest
	(*ListWorkersResponse)(nil),    // 28: scheduler.ListWorkersResponse
	(*TaskCompletionRequest)(nil),  // 29: scheduler.TaskCompletionRequest
	(*TaskCompletionResponse)(nil), // 30: scheduler.TaskCompletionResponse
	nil,                            // 31: scheduler.Task.MetaEntry
	nil,                            // 32: scheduler.Worker.MetaEntry
	nil,                            // 33: scheduler.AssignRequest.MetaEntry
	nil,                            // 34: scheduler.Assignment.MetaEntry
	nil,                            // 35: scheduler.TaskCompletionRequest.ResourceUsageEntry
	(*structpb.Struct)(nil),        // 36: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 37: google.protobuf.Timestamp
}
var file_scheduler_proto_depIdxs = []int32{
	31, // 0: scheduler.Task.meta:type_name -> scheduler.Task.MetaEntry
	0,  // 1: scheduler.Task.exec_pref:type_name -> scheduler.ExecPreference
	36, // 2: scheduler.Task.extra:type_name -> google.protobuf.Struct
	1,  // 3: scheduler.Worker.exec_modes:type_name -> scheduler.ExecutionMode
	32, // 4: scheduler.Worker.meta:type_name -> scheduler.Worker.MetaEntry
	36, // 5: scheduler.Worker.extra:type_name -> google.protobuf.Struct
	36, // 6: scheduler.Heartbeat.extra:type_name -> google.protobuf.Struct
	37, // 7: scheduler.Heartbeat.ts:type_name -> google.protobuf.Timestamp
	1,  // 8: scheduler.AssignRequest.exec_mode:type_name -> scheduler.ExecutionMode
	33, // 9: scheduler.AssignRequest.meta:type_name -> scheduler.AssignRequest.MetaEntry
	4,  // 10: scheduler.PlanRequest.tasks:type_name -> scheduler.Task
	5,  // 11: scheduler.PlanRequest.workers:type_name -> scheduler.Worker
	10, // 12: scheduler.PlanRequest.objectives:type_name -> scheduler.Objective
	11, // 13: scheduler.PlanRequest.constraints:type_name -> scheduler.Constraint
	12, // 14: scheduler.PlanRequest.options:type_name -> scheduler.PlanOptions
	2,  // 15: scheduler.Objective.type:type_name -> scheduler.Objective.Type
	36, // 16: scheduler.PlanOptions.extra:type_name -> google.protobuf.Struct
	1,  // 17: scheduler.Assignment.exec_mode:type_name -> scheduler.ExecutionMode
	34, // 18: scheduler.Assignment.meta:type_name -> scheduler.Assignment.MetaEntry
	13, // 19: scheduler.PlanResponse.assignments:type_name -> scheduler.Assignment
	37, // 20: scheduler.PlanResponse.generated_ts:type_name -> google.protobuf.Timestamp
	36, // 21: scheduler.PlanResponse.extra:type_name -> google.protobuf.Struct
	4,  // 22: scheduler.ReplanRequest.tasks:type_name -> scheduler.Task
	5,  // 23: scheduler.ReplanRequest.workers:type_name -> scheduler.Worker
	16, // 24: scheduler.ReplanRequest.events:type_name -> scheduler.PlannerEvent
	12, // 25: scheduler.ReplanRequest.options:type_name -> scheduler.PlanOptions
	3,  // 26: scheduler.PlannerEvent.type:type_name -> scheduler.PlannerEvent.Type
	37, // 27: scheduler.PlannerEvent.ts:type_name -> google.protobuf.Timestamp
	36, // 28: scheduler.PlannerEvent.extra:type_name -> google.protobuf.Struct
	4,  // 29: scheduler.SubmitTaskRequest.task:type_name -> scheduler.Task
	5,  // 30: scheduler.RegisterWorkerRequest.worker:type_name -> scheduler.Worker
	5,  // 31: scheduler.HeartbeatRequest.worker:type_name -> scheduler.Worker
	5,  // 32: scheduler.ListWorkersResponse.workers:type_name -> scheduler.Worker
	35, // 33: scheduler.TaskCompletionRequest.resource_usage:type_name -> scheduler.TaskCompletionRequest.ResourceUsageEntry
	17, // 34: scheduler.SchedulerService.SubmitTask:input_type -> scheduler.SubmitTaskRequest
	19, // 35: scheduler.SchedulerService.GetTaskStatus:input_type -> scheduler.GetTaskStatusRequest
	21, // 36: scheduler.SchedulerService.CancelTask:input_type -> scheduler.CancelTaskRequest
	23, // 37: scheduler.SchedulerService.RegisterWorker:input_type -> scheduler.RegisterWorkerRequest
	25, // 38: scheduler.SchedulerService.Heartbeat:input_type -> scheduler.HeartbeatRequest
	27, // 39: scheduler.SchedulerService.ListWorkers:input_type -> scheduler.ListWorkersRequest
	29, // 40: scheduler.SchedulerService.ReportTaskCompletion:input_type -> scheduler.TaskCompletionRequest
	9,  // 41: scheduler.Planner.Plan:input_type -> scheduler.PlanRequest
	15, // 42: scheduler.Planner.Replan:input_type -> scheduler.ReplanRequest
	18, // 43: scheduler.SchedulerService.SubmitTask:output_type -> scheduler.SubmitTaskResponse
	20, // 44: scheduler.SchedulerService.GetTaskStatus:output_type -> scheduler.GetTaskStatusResponse
	22, // 45: scheduler.SchedulerService.CancelTask:output_type -> scheduler.CancelTaskResponse
	24, // 46: scheduler.SchedulerService.RegisterWorker:output_type -> scheduler.RegisterWorkerResponse
	26, // 47: scheduler.SchedulerService.Heartbeat:output_type -> scheduler.HeartbeatResponse
	28, // 48: scheduler.SchedulerService.ListWorkers:output_type -> scheduler.ListWorkersResponse
	30, // 49: scheduler.SchedulerService.ReportTaskCompletion:output_type -> scheduler.TaskCompletionResponse
	14, // 50: scheduler.Planner.Plan:output_type -> scheduler.PlanResponse
	14, // 51: scheduler.Planner.Replan:output_type -> scheduler.PlanResponse
	43, // [43:52] is the sub-list for method output_type
	34, // [34:43] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		EnumInfos:         file_scheduler_proto_enumTypes,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
