// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: scheduler.proto

package proto

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Planner_Plan_FullMethodName   = "/scheduler.Planner/Plan"
	Planner_Replan_FullMethodName = "/scheduler.Planner/Replan"
)

// PlannerClient is the client API for Planner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlannerClient interface {
	// Compute a plan for the provided tasks and workers. Planner should
	// attempt to respect planning_time_budget_sec and objectives.
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	// Replan based on events and optional previous plan id.
	Replan(ctx context.Context, in *ReplanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
}

type plannerClient struct {
	cc grpc.ClientConnInterface
}

func NewPlannerClient(cc grpc.ClientConnInterface) PlannerClient {
	return &plannerClient{cc}
}

func (c *plannerClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, Planner_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plannerClient) Replan(ctx context.Context, in *ReplanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, Planner_Replan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlannerServer is the server API for Planner service.
// All implementations must embed UnimplementedPlannerServer
// for forward compatibility.
type PlannerServer interface {
	// Compute a plan for the provided tasks and workers. Planner should
	// attempt to respect planning_time_budget_sec and objectives.
	Plan(context.Context, *PlanRequest) (*PlanResponse, error)
	// Replan based on events and optional previous plan id.
	Replan(context.Context, *ReplanRequest) (*PlanResponse, error)
	mustEmbedUnimplementedPlannerServer()
}

// UnimplementedPlannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlannerServer struct{}

func (UnimplementedPlannerServer) Plan(context.Context, *PlanRequest) (*PlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedPlannerServer) Replan(context.Context, *ReplanRequest) (*PlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replan not implemented")
}
func (UnimplementedPlannerServer) mustEmbedUnimplementedPlannerServer() {}
func (UnimplementedPlannerServer) testEmbeddedByValue()                 {}

// UnsafePlannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlannerServer will
// result in compilation errors.
type UnsafePlannerServer interface {
	mustEmbedUnimplementedPlannerServer()
}

func RegisterPlannerServer(s grpc.ServiceRegistrar, srv PlannerServer) {
	// If the following call pancis, it indicates UnimplementedPlannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Planner_ServiceDesc, srv)
}

func _Planner_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Planner_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Planner_Replan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServer).Replan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Planner_Replan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServer).Replan(ctx, req.(*ReplanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Planner_ServiceDesc is the grpc.ServiceDesc for Planner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Planner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.Planner",
	HandlerType: (*PlannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plan",
			Handler:    _Planner_Plan_Handler,
		},
		{
			MethodName: "Replan",
			Handler:    _Planner_Replan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler.proto",
}
